/* ============================================================
   DATA STATIS APLIKASI
   - Kosakata HSK 1-4 (hanzi, pinyin, arti Indonesia, level, contoh)
   - Program latihan mingguan
   - Referensi kalori makanan umum (Indonesia)
   ============================================================ */

/* ---------- KOSAKATA HSK 1-4 ----------
   h = hanzi, p = pinyin, a = arti (Indonesia), l = level HSK, c = contoh kalimat */
const HSK_VOCAB = [
  // ===================== HSK 1 =====================
  { h: "你", p: "nǐ", a: "kamu", l: 1, c: "你好吗？(Apa kabar?)" },
  { h: "好", p: "hǎo", a: "baik / bagus", l: 1, c: "我很好。(Saya baik.)" },
  { h: "我", p: "wǒ", a: "saya / aku", l: 1, c: "我是学生。(Saya murid.)" },
  { h: "是", p: "shì", a: "adalah / iya", l: 1, c: "他是老师。(Dia guru.)" },
  { h: "他", p: "tā", a: "dia (laki-laki)", l: 1 },
  { h: "她", p: "tā", a: "dia (perempuan)", l: 1 },
  { h: "不", p: "bù", a: "tidak", l: 1, c: "我不喝茶。(Saya tidak minum teh.)" },
  { h: "人", p: "rén", a: "orang", l: 1 },
  { h: "大", p: "dà", a: "besar", l: 1 },
  { h: "小", p: "xiǎo", a: "kecil", l: 1 },
  { h: "中国", p: "zhōngguó", a: "Tiongkok / China", l: 1 },
  { h: "学生", p: "xuéshēng", a: "murid / pelajar", l: 1 },
  { h: "老师", p: "lǎoshī", a: "guru", l: 1 },
  { h: "朋友", p: "péngyǒu", a: "teman", l: 1 },
  { h: "家", p: "jiā", a: "rumah / keluarga", l: 1 },
  { h: "爱", p: "ài", a: "cinta / menyukai", l: 1 },
  { h: "喜欢", p: "xǐhuān", a: "suka", l: 1, c: "我喜欢中国菜。(Saya suka masakan China.)" },
  { h: "吃", p: "chī", a: "makan", l: 1, c: "你吃饭了吗？(Sudah makan?)" },
  { h: "喝", p: "hē", a: "minum", l: 1 },
  { h: "水", p: "shuǐ", a: "air", l: 1 },
  { h: "菜", p: "cài", a: "sayur / masakan", l: 1 },
  { h: "米饭", p: "mǐfàn", a: "nasi", l: 1 },
  { h: "茶", p: "chá", a: "teh", l: 1 },
  { h: "看", p: "kàn", a: "melihat / membaca", l: 1 },
  { h: "听", p: "tīng", a: "mendengar", l: 1 },
  { h: "说", p: "shuō", a: "berbicara", l: 1 },
  { h: "写", p: "xiě", a: "menulis", l: 1 },
  { h: "读", p: "dú", a: "membaca", l: 1 },
  { h: "书", p: "shū", a: "buku", l: 1 },
  { h: "名字", p: "míngzì", a: "nama", l: 1 },
  { h: "今天", p: "jīntiān", a: "hari ini", l: 1 },
  { h: "明天", p: "míngtiān", a: "besok", l: 1 },
  { h: "昨天", p: "zuótiān", a: "kemarin", l: 1 },
  { h: "年", p: "nián", a: "tahun", l: 1 },
  { h: "月", p: "yuè", a: "bulan", l: 1 },
  { h: "星期", p: "xīngqī", a: "minggu (pekan)", l: 1 },
  { h: "现在", p: "xiànzài", a: "sekarang", l: 1 },
  { h: "点", p: "diǎn", a: "jam / titik", l: 1, c: "现在三点。(Sekarang jam 3.)" },
  { h: "钱", p: "qián", a: "uang", l: 1 },
  { h: "买", p: "mǎi", a: "membeli", l: 1 },
  { h: "去", p: "qù", a: "pergi", l: 1, c: "我去学校。(Saya pergi ke sekolah.)" },
  { h: "来", p: "lái", a: "datang", l: 1 },
  { h: "回", p: "huí", a: "kembali / pulang", l: 1 },
  { h: "开", p: "kāi", a: "membuka / menyalakan", l: 1 },
  { h: "住", p: "zhù", a: "tinggal", l: 1 },
  { h: "工作", p: "gōngzuò", a: "bekerja / pekerjaan", l: 1 },
  { h: "学校", p: "xuéxiào", a: "sekolah", l: 1 },
  { h: "天气", p: "tiānqì", a: "cuaca", l: 1 },
  { h: "谢谢", p: "xièxie", a: "terima kasih", l: 1 },
  { h: "再见", p: "zàijiàn", a: "sampai jumpa", l: 1 },
  { h: "一", p: "yī", a: "satu (1)", l: 1 },
  { h: "二", p: "èr", a: "dua (2)", l: 1 },
  { h: "三", p: "sān", a: "tiga (3)", l: 1 },
  { h: "五", p: "wǔ", a: "lima (5)", l: 1 },
  { h: "十", p: "shí", a: "sepuluh (10)", l: 1 },

  // ===================== HSK 2 =====================
  { h: "知道", p: "zhīdào", a: "tahu / mengetahui", l: 2 },
  { h: "觉得", p: "juéde", a: "merasa / berpendapat", l: 2 },
  { h: "因为", p: "yīnwèi", a: "karena", l: 2 },
  { h: "所以", p: "suǒyǐ", a: "maka / oleh karena itu", l: 2 },
  { h: "但是", p: "dànshì", a: "tetapi", l: 2 },
  { h: "还是", p: "háishì", a: "atau / tetap", l: 2 },
  { h: "可能", p: "kěnéng", a: "mungkin", l: 2 },
  { h: "应该", p: "yīnggāi", a: "seharusnya", l: 2 },
  { h: "希望", p: "xīwàng", a: "berharap", l: 2 },
  { h: "帮助", p: "bāngzhù", a: "membantu / bantuan", l: 2 },
  { h: "介绍", p: "jièshào", a: "memperkenalkan", l: 2 },
  { h: "准备", p: "zhǔnbèi", a: "bersiap / menyiapkan", l: 2 },
  { h: "开始", p: "kāishǐ", a: "mulai", l: 2 },
  { h: "完成", p: "wánchéng", a: "menyelesaikan", l: 2 },
  { h: "运动", p: "yùndòng", a: "olahraga", l: 2, c: "我每天运动。(Saya olahraga setiap hari.)" },
  { h: "跑步", p: "pǎobù", a: "berlari / lari", l: 2, c: "我喜欢跑步。(Saya suka lari.)" },
  { h: "身体", p: "shēntǐ", a: "tubuh / badan", l: 2 },
  { h: "健康", p: "jiànkāng", a: "sehat / kesehatan", l: 2 },
  { h: "累", p: "lèi", a: "lelah", l: 2 },
  { h: "忙", p: "máng", a: "sibuk", l: 2 },
  { h: "快", p: "kuài", a: "cepat", l: 2 },
  { h: "慢", p: "màn", a: "lambat", l: 2 },
  { h: "高", p: "gāo", a: "tinggi", l: 2 },
  { h: "新", p: "xīn", a: "baru", l: 2 },
  { h: "旧", p: "jiù", a: "lama / usang", l: 2 },
  { h: "贵", p: "guì", a: "mahal", l: 2 },
  { h: "便宜", p: "piányi", a: "murah", l: 2 },
  { h: "颜色", p: "yánsè", a: "warna", l: 2 },
  { h: "白", p: "bái", a: "putih", l: 2 },
  { h: "黑", p: "hēi", a: "hitam", l: 2 },
  { h: "红", p: "hóng", a: "merah", l: 2 },
  { h: "鸡蛋", p: "jīdàn", a: "telur ayam", l: 2 },
  { h: "牛奶", p: "niúnǎi", a: "susu sapi", l: 2 },
  { h: "羊肉", p: "yángròu", a: "daging kambing", l: 2 },
  { h: "鱼", p: "yú", a: "ikan", l: 2 },
  { h: "西瓜", p: "xīguā", a: "semangka", l: 2 },
  { h: "咖啡", p: "kāfēi", a: "kopi", l: 2 },
  { h: "时间", p: "shíjiān", a: "waktu", l: 2 },
  { h: "早上", p: "zǎoshang", a: "pagi", l: 2 },
  { h: "晚上", p: "wǎnshang", a: "malam", l: 2 },
  { h: "中午", p: "zhōngwǔ", a: "tengah hari / siang", l: 2 },
  { h: "小时", p: "xiǎoshí", a: "jam (durasi)", l: 2 },
  { h: "公司", p: "gōngsī", a: "perusahaan", l: 2 },
  { h: "问题", p: "wèntí", a: "masalah / pertanyaan", l: 2 },
  { h: "事情", p: "shìqing", a: "urusan / hal", l: 2 },
  { h: "意思", p: "yìsi", a: "arti / maksud", l: 2 },
  { h: "旅游", p: "lǚyóu", a: "berwisata", l: 2 },
  { h: "机场", p: "jīchǎng", a: "bandara", l: 2 },
  { h: "火车", p: "huǒchē", a: "kereta api", l: 2 },
  { h: "手机", p: "shǒujī", a: "ponsel / HP", l: 2 },

  // ===================== HSK 3 =====================
  { h: "经常", p: "jīngcháng", a: "sering", l: 3 },
  { h: "一般", p: "yìbān", a: "biasanya / umumnya", l: 3 },
  { h: "突然", p: "tūrán", a: "tiba-tiba", l: 3 },
  { h: "终于", p: "zhōngyú", a: "akhirnya", l: 3 },
  { h: "其实", p: "qíshí", a: "sebenarnya", l: 3 },
  { h: "比较", p: "bǐjiào", a: "relatif / membandingkan", l: 3 },
  { h: "特别", p: "tèbié", a: "khususnya / istimewa", l: 3 },
  { h: "重要", p: "zhòngyào", a: "penting", l: 3 },
  { h: "简单", p: "jiǎndān", a: "sederhana / mudah", l: 3 },
  { h: "容易", p: "róngyì", a: "mudah", l: 3 },
  { h: "难", p: "nán", a: "sulit", l: 3 },
  { h: "清楚", p: "qīngchu", a: "jelas", l: 3 },
  { h: "habit", p: "xíguàn", a: "kebiasaan", l: 3, c: "好习惯很重要。(Kebiasaan baik itu penting.)" },
  { h: "习惯", p: "xíguàn", a: "kebiasaan / terbiasa", l: 3 },
  { h: "决定", p: "juédìng", a: "memutuskan / keputusan", l: 3 },
  { h: "选择", p: "xuǎnzé", a: "memilih / pilihan", l: 3 },
  { h: "努力", p: "nǔlì", a: "berusaha keras", l: 3, c: "我会努力学习。(Saya akan belajar keras.)" },
  { h: "提高", p: "tígāo", a: "meningkatkan", l: 3 },
  { h: "影响", p: "yǐngxiǎng", a: "memengaruhi / pengaruh", l: 3 },
  { h: "解决", p: "jiějué", a: "menyelesaikan / mengatasi", l: 3 },
  { h: "检查", p: "jiǎnchá", a: "memeriksa", l: 3 },
  { h: "锻炼", p: "duànliàn", a: "berolahraga / melatih diri", l: 3, c: "锻炼身体很健康。(Olahraga menyehatkan badan.)" },
  { h: "健身", p: "jiànshēn", a: "fitness / nge-gym", l: 3 },
  { h: "比赛", p: "bǐsài", a: "pertandingan", l: 3 },
  { h: "成绩", p: "chéngjì", a: "hasil / prestasi", l: 3 },
  { h: "calories", p: "rèliàng", a: "kalori / energi panas", l: 3 },
  { h: "热量", p: "rèliàng", a: "kalori / energi panas", l: 3 },
  { h: "减肥", p: "jiǎnféi", a: "menurunkan berat badan", l: 3, c: "我想减肥。(Saya ingin menurunkan BB.)" },
  { h: "体重", p: "tǐzhòng", a: "berat badan", l: 3 },
  { h: "公斤", p: "gōngjīn", a: "kilogram (kg)", l: 3 },
  { h: "习题", p: "xítí", a: "soal latihan", l: 3 },
  { h: "复习", p: "fùxí", a: "mengulang pelajaran", l: 3 },
  { h: "练习", p: "liànxí", a: "berlatih / latihan", l: 3 },
  { h: "记得", p: "jìde", a: "ingat", l: 3 },
  { h: "忘记", p: "wàngjì", a: "lupa", l: 3 },
  { h: "burung", p: "niǎo", a: "burung", l: 3 },
  { h: "环境", p: "huánjìng", a: "lingkungan", l: 3 },
  { h: "城市", p: "chéngshì", a: "kota", l: 3 },
  { h: "地方", p: "dìfang", a: "tempat", l: 3 },
  { h: "附近", p: "fùjìn", a: "sekitar / dekat", l: 3 },
  { h: "邻居", p: "línjū", a: "tetangga", l: 3 },
  { h: "经理", p: "jīnglǐ", a: "manajer", l: 3 },
  { h: "护照", p: "hùzhào", a: "paspor", l: 3 },
  { h: "节目", p: "jiémù", a: "acara / program", l: 3 },
  { h: "新闻", p: "xīnwén", a: "berita", l: 3 },
  { h: "故事", p: "gùshi", a: "cerita", l: 3 },
  { h: "结婚", p: "jiéhūn", a: "menikah", l: 3 },
  { h: "年轻", p: "niánqīng", a: "muda", l: 3 },
  { h: "聪明", p: "cōngming", a: "pintar / cerdas", l: 3 },
  { h: "认真", p: "rènzhēn", a: "serius / tekun", l: 3 },
  { h: "满意", p: "mǎnyì", a: "puas", l: 3 },

  // ===================== HSK 4 =====================
  { h: "坚持", p: "jiānchí", a: "bertahan / konsisten", l: 4, c: "坚持锻炼很重要。(Konsisten berolahraga itu penting.)" },
  { h: "鼓励", p: "gǔlì", a: "menyemangati / dorongan", l: 4 },
  { h: "积极", p: "jījí", a: "aktif / positif", l: 4 },
  { h: "respect", p: "zūnzhòng", a: "menghormati", l: 4 },
  { h: "尊重", p: "zūnzhòng", a: "menghormati", l: 4 },
  { h: "建议", p: "jiànyì", a: "menyarankan / saran", l: 4 },
  { h: "judge", p: "pànduàn", a: "menilai / menentukan", l: 4 },
  { h: "判断", p: "pànduàn", a: "menilai / menentukan", l: 4 },
  { h: "考虑", p: "kǎolǜ", a: "mempertimbangkan", l: 4 },
  { h: "实际", p: "shíjì", a: "nyata / aktual", l: 4 },
  { h: "估计", p: "gūjì", a: "memperkirakan / estimasi", l: 4, c: "我估计明天会下雨。(Saya perkirakan besok hujan.)" },
  { h: "增加", p: "zēngjiā", a: "menambah / meningkat", l: 4 },
  { h: "减少", p: "jiǎnshǎo", a: "mengurangi / berkurang", l: 4 },
  { h: "改变", p: "gǎibiàn", a: "mengubah / perubahan", l: 4 },
  { h: "保持", p: "bǎochí", a: "menjaga / mempertahankan", l: 4, c: "保持健康很重要。(Menjaga kesehatan itu penting.)" },
  { h: "计划", p: "jìhuà", a: "rencana / merencanakan", l: 4 },
  { h: "目标", p: "mùbiāo", a: "target / tujuan", l: 4, c: "我的目标是减肥。(Targetku adalah menurunkan BB.)" },
  { h: "结果", p: "jiéguǒ", a: "hasil", l: 4 },
  { h: "过程", p: "guòchéng", a: "proses", l: 4 },
  { h: "方法", p: "fāngfǎ", a: "metode / cara", l: 4 },
  { h: "效果", p: "xiàoguǒ", a: "efek / hasil", l: 4 },
  { h: "经验", p: "jīngyàn", a: "pengalaman", l: 4 },
  { h: "能力", p: "nénglì", a: "kemampuan", l: 4 },
  { h: "机会", p: "jīhuì", a: "kesempatan", l: 4 },
  { h: "责任", p: "zérèn", a: "tanggung jawab", l: 4 },
  { h: "压力", p: "yālì", a: "tekanan / stres", l: 4 },
  { h: "情况", p: "qíngkuàng", a: "situasi / keadaan", l: 4 },
  { h: "区别", p: "qūbié", a: "perbedaan", l: 4 },
  { h: "标准", p: "biāozhǔn", a: "standar", l: 4 },
  { h: "重点", p: "zhòngdiǎn", a: "fokus / poin utama", l: 4 },
  { h: "肌肉", p: "jīròu", a: "otot", l: 4, c: "运动可以增加肌肉。(Olahraga bisa menambah otot.)" },
  { h: "脂肪", p: "zhīfáng", a: "lemak", l: 4 },
  { h: "营养", p: "yíngyǎng", a: "nutrisi / gizi", l: 4 },
  { h: "蛋白质", p: "dànbáizhì", a: "protein", l: 4 },
  { h: "饮食", p: "yǐnshí", a: "pola makan", l: 4 },
  { h: "肚子", p: "dùzi", a: "perut", l: 4, c: "我想减小肚子。(Saya ingin mengecilkan perut.)" },
  { h: "出汗", p: "chūhàn", a: "berkeringat", l: 4 },
  { h: "呼吸", p: "hūxī", a: "bernapas / napas", l: 4 },
  { h: "速度", p: "sùdù", a: "kecepatan", l: 4 },
  { h: "距离", p: "jùlí", a: "jarak", l: 4 },
  { h: "汗", p: "hàn", a: "keringat", l: 4 },
  { h: "羽毛球", p: "yǔmáoqiú", a: "bulu tangkis", l: 4, c: "周六我打羽毛球。(Sabtu saya main bulu tangkis.)" },
  { h: "毕业", p: "bìyè", a: "lulus / wisuda", l: 4 },
  { h: "professional", p: "zhuānyè", a: "jurusan / profesional", l: 4 },
  { h: "专业", p: "zhuānyè", a: "jurusan / profesional", l: 4 },
  { h: "收入", p: "shōurù", a: "pendapatan", l: 4 },
  { h: "节约", p: "jiéyuē", a: "berhemat", l: 4 },
  { h: "丰富", p: "fēngfù", a: "kaya / berlimpah", l: 4 },
  { h: "复杂", p: "fùzá", a: "rumit / kompleks", l: 4 },
  { h: "正式", p: "zhèngshì", a: "resmi / formal", l: 4 },
  { h: "优秀", p: "yōuxiù", a: "unggul / berprestasi", l: 4 },
];

// Bersihkan entri "placeholder" (kunci bahasa Inggris) yang dipakai saat penyusunan:
// hapus entri yang hanzi-nya bukan karakter China.
const VOCAB = HSK_VOCAB.filter(v => /[一-鿿]/.test(v.h))
  .map((v, i) => ({ id: "v" + i, ...v }));

/* ---------- PROGRAM LATIHAN MINGGUAN ----------
   Disusun untuk fat loss + mengecilkan perut (banyak compound + core + kardio).
   key = indeks hari getDay() (0=Minggu ... 6=Sabtu) */
const PROGRAM = {
  1: { // Senin
    nama: "Upper Body", emoji: "💪", fokus: "Dada, punggung, lengan",
    exercises: [
      { n: "Pull-up / Lat Pulldown", d: "3 × 8-12" },
      { n: "Bench Press / Push-up", d: "3 × 10-12" },
      { n: "Seated Row", d: "3 × 12" },
      { n: "Overhead Press", d: "3 × 10" },
      { n: "Bicep Curl", d: "3 × 12" },
      { n: "Tricep Dip", d: "3 × 12" },
      { n: "Plank (core)", d: "3 × 45 dtk" },
    ],
    cardio: null, target: 45,
  },
  2: { // Selasa
    nama: "Lari + Bodyweight", emoji: "🏃", fokus: "Kardio & ketahanan",
    exercises: [
      { n: "Push-up", d: "4 × 15" },
      { n: "Bodyweight Squat", d: "4 × 20" },
      { n: "Walking Lunges", d: "3 × 12/kaki" },
      { n: "Mountain Climbers", d: "3 × 30 dtk" },
      { n: "Burpees", d: "3 × 10" },
      { n: "Plank (core)", d: "3 × 45 dtk" },
    ],
    cardio: { jenis: "Lari", durasi: 30 }, target: 45,
  },
  3: { // Rabu
    nama: "Lower Body", emoji: "🦵", fokus: "Kaki & glutes",
    exercises: [
      { n: "Squat (barbell/dumbbell)", d: "4 × 8-12" },
      { n: "Romanian Deadlift", d: "3 × 10" },
      { n: "Leg Press", d: "3 × 12" },
      { n: "Walking Lunges", d: "3 × 12/kaki" },
      { n: "Calf Raise", d: "4 × 15" },
      { n: "Hanging Leg Raise (core)", d: "3 × 12" },
    ],
    cardio: null, target: 45,
  },
  4: { // Kamis
    nama: "Trisep & Bahu", emoji: "🏋️", fokus: "Bahu & trisep",
    exercises: [
      { n: "Overhead Press", d: "4 × 8-12" },
      { n: "Lateral Raise", d: "3 × 15" },
      { n: "Front Raise", d: "3 × 12" },
      { n: "Tricep Pushdown", d: "3 × 12" },
      { n: "Skull Crusher", d: "3 × 12" },
      { n: "Face Pull", d: "3 × 15" },
      { n: "Bicycle Crunch (core)", d: "3 × 20" },
    ],
    cardio: null, target: 45,
  },
  5: { // Jumat
    nama: "Istirahat / Lari Ringan", emoji: "😌", fokus: "Recovery aktif",
    exercises: [
      { n: "Stretching / Mobility", d: "10-15 mnt" },
      { n: "Plank (opsional)", d: "3 × 45 dtk" },
    ],
    cardio: { jenis: "Lari ringan (opsional)", durasi: 30 }, target: 30,
  },
  6: { // Sabtu
    nama: "Dada & Bicep + Badminton", emoji: "🏸", fokus: "Dada, bicep & badminton (14.00-16.00)",
    exercises: [
      { n: "Bench Press", d: "4 × 8-12" },
      { n: "Incline Dumbbell Press", d: "3 × 10" },
      { n: "Chest Fly", d: "3 × 12" },
      { n: "Push-up", d: "3 × max" },
      { n: "Barbell/Dumbbell Curl", d: "3 × 12" },
      { n: "Hammer Curl", d: "3 × 12" },
      { n: "Badminton 🏸", d: "14.00 - 16.00" },
    ],
    cardio: { jenis: "Badminton", durasi: 120 }, target: 60,
  },
  0: { // Minggu
    nama: "Lari + Kardio", emoji: "🔥", fokus: "Kardio & pembakaran lemak + timbang BB",
    exercises: [
      { n: "Lari", d: "30-40 mnt" },
      { n: "HIIT (sprint interval)", d: "10 mnt" },
      { n: "Jumping Jack", d: "3 × 40" },
      { n: "Russian Twist (core)", d: "3 × 20" },
      { n: "Leg Raise (core)", d: "3 × 15" },
      { n: "Plank (core)", d: "3 × 60 dtk" },
    ],
    cardio: { jenis: "Lari + Kardio", durasi: 40 }, target: 50,
  },
};

const NAMA_HARI = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"];

// Perkiraan kalori terbakar per menit (kasar, untuk estimasi)
const KALORI_PER_MENIT = {
  "Lari": 11,
  "Lari ringan (opsional)": 8,
  "Badminton": 7,
  "Lari + Kardio": 10,
  "Angkat beban / Gym": 6,
  "HIIT": 12,
  "Lainnya": 6,
};

/* ---------- REFERENSI KALORI MAKANAN (per porsi umum) ---------- */
const FOOD_REF = [
  { n: "Nasi putih (1 centong ~100g)", k: 175 },
  { n: "Nasi merah (100g)", k: 150 },
  { n: "Ayam goreng (1 potong)", k: 260 },
  { n: "Ayam dada rebus (100g)", k: 165 },
  { n: "Telur rebus (1 butir)", k: 78 },
  { n: "Telur dadar (1 butir)", k: 150 },
  { n: "Tahu (1 potong)", k: 80 },
  { n: "Tempe (1 potong)", k: 100 },
  { n: "Ikan bakar (100g)", k: 180 },
  { n: "Daging sapi (100g)", k: 250 },
  { n: "Sayur bayam (1 mangkok)", k: 40 },
  { n: "Tumis kangkung (1 porsi)", k: 90 },
  { n: "Mie instan (1 bungkus)", k: 380 },
  { n: "Roti tawar (1 lembar)", k: 80 },
  { n: "Pisang (1 buah)", k: 105 },
  { n: "Apel (1 buah)", k: 95 },
  { n: "Susu (1 gelas)", k: 120 },
  { n: "Kopi susu gula (1 gelas)", k: 150 },
  { n: "Teh manis (1 gelas)", k: 90 },
  { n: "Air putih", k: 0 },
  { n: "Gorengan (1 buah)", k: 130 },
  { n: "Bakso (1 mangkok)", k: 300 },
  { n: "Soto ayam (1 mangkok)", k: 312 },
  { n: "Nasi goreng (1 piring)", k: 330 },
  { n: "Whey protein (1 scoop)", k: 120 },
  { n: "Oatmeal (40g)", k: 150 },
  { n: "Kacang almond (10 butir)", k: 70 },
  { n: "Alpukat (1/2 buah)", k: 160 },
];
