/* ============================================================
   DATA STATIS APLIKASI
   - Kosakata HSK 1-4 (hanzi, pinyin, arti Indonesia, level, contoh)
   - Program latihan mingguan
   - Referensi kalori makanan umum (Indonesia)
   ============================================================ */

/* ---------- KOSAKATA HSK 1-4 ----------
   h = hanzi, p = pinyin, a = arti (Indonesia), l = level HSK, c = contoh kalimat */
const HSK_VOCAB = [
  // ===================== HSK 1 =====================
  { h: "你", p: "nǐ", a: "kamu", l: 1, c: "你好吗？(Apa kabar?)" },
  { h: "好", p: "hǎo", a: "baik / bagus", l: 1, c: "我很好。(Saya baik.)" },
  { h: "我", p: "wǒ", a: "saya / aku", l: 1, c: "我是学生。(Saya murid.)" },
  { h: "是", p: "shì", a: "adalah / iya", l: 1, c: "他是老师。(Dia guru.)" },
  { h: "他", p: "tā", a: "dia (laki-laki)", l: 1 },
  { h: "她", p: "tā", a: "dia (perempuan)", l: 1 },
  { h: "不", p: "bù", a: "tidak", l: 1, c: "我不喝茶。(Saya tidak minum teh.)" },
  { h: "人", p: "rén", a: "orang", l: 1 },
  { h: "大", p: "dà", a: "besar", l: 1 },
  { h: "小", p: "xiǎo", a: "kecil", l: 1 },
  { h: "中国", p: "zhōngguó", a: "Tiongkok / China", l: 1 },
  { h: "学生", p: "xuéshēng", a: "murid / pelajar", l: 1 },
  { h: "老师", p: "lǎoshī", a: "guru", l: 1 },
  { h: "朋友", p: "péngyǒu", a: "teman", l: 1 },
  { h: "家", p: "jiā", a: "rumah / keluarga", l: 1 },
  { h: "爱", p: "ài", a: "cinta / menyukai", l: 1 },
  { h: "喜欢", p: "xǐhuān", a: "suka", l: 1, c: "我喜欢中国菜。(Saya suka masakan China.)" },
  { h: "吃", p: "chī", a: "makan", l: 1, c: "你吃饭了吗？(Sudah makan?)" },
  { h: "喝", p: "hē", a: "minum", l: 1 },
  { h: "水", p: "shuǐ", a: "air", l: 1 },
  { h: "菜", p: "cài", a: "sayur / masakan", l: 1 },
  { h: "米饭", p: "mǐfàn", a: "nasi", l: 1 },
  { h: "茶", p: "chá", a: "teh", l: 1 },
  { h: "看", p: "kàn", a: "melihat / membaca", l: 1 },
  { h: "听", p: "tīng", a: "mendengar", l: 1 },
  { h: "说", p: "shuō", a: "berbicara", l: 1 },
  { h: "写", p: "xiě", a: "menulis", l: 1 },
  { h: "读", p: "dú", a: "membaca", l: 1 },
  { h: "书", p: "shū", a: "buku", l: 1 },
  { h: "名字", p: "míngzì", a: "nama", l: 1 },
  { h: "今天", p: "jīntiān", a: "hari ini", l: 1 },
  { h: "明天", p: "míngtiān", a: "besok", l: 1 },
  { h: "昨天", p: "zuótiān", a: "kemarin", l: 1 },
  { h: "年", p: "nián", a: "tahun", l: 1 },
  { h: "月", p: "yuè", a: "bulan", l: 1 },
  { h: "星期", p: "xīngqī", a: "minggu (pekan)", l: 1 },
  { h: "现在", p: "xiànzài", a: "sekarang", l: 1 },
  { h: "点", p: "diǎn", a: "jam / titik", l: 1, c: "现在三点。(Sekarang jam 3.)" },
  { h: "钱", p: "qián", a: "uang", l: 1 },
  { h: "买", p: "mǎi", a: "membeli", l: 1 },
  { h: "去", p: "qù", a: "pergi", l: 1, c: "我去学校。(Saya pergi ke sekolah.)" },
  { h: "来", p: "lái", a: "datang", l: 1 },
  { h: "回", p: "huí", a: "kembali / pulang", l: 1 },
  { h: "开", p: "kāi", a: "membuka / menyalakan", l: 1 },
  { h: "住", p: "zhù", a: "tinggal", l: 1 },
  { h: "工作", p: "gōngzuò", a: "bekerja / pekerjaan", l: 1 },
  { h: "学校", p: "xuéxiào", a: "sekolah", l: 1 },
  { h: "天气", p: "tiānqì", a: "cuaca", l: 1 },
  { h: "谢谢", p: "xièxie", a: "terima kasih", l: 1 },
  { h: "再见", p: "zàijiàn", a: "sampai jumpa", l: 1 },
  { h: "一", p: "yī", a: "satu (1)", l: 1 },
  { h: "二", p: "èr", a: "dua (2)", l: 1 },
  { h: "三", p: "sān", a: "tiga (3)", l: 1 },
  { h: "五", p: "wǔ", a: "lima (5)", l: 1 },
  { h: "十", p: "shí", a: "sepuluh (10)", l: 1 },

  // ===================== HSK 2 =====================
  { h: "知道", p: "zhīdào", a: "tahu / mengetahui", l: 2 },
  { h: "觉得", p: "juéde", a: "merasa / berpendapat", l: 2 },
  { h: "因为", p: "yīnwèi", a: "karena", l: 2 },
  { h: "所以", p: "suǒyǐ", a: "maka / oleh karena itu", l: 2 },
  { h: "但是", p: "dànshì", a: "tetapi", l: 2 },
  { h: "还是", p: "háishì", a: "atau / tetap", l: 2 },
  { h: "可能", p: "kěnéng", a: "mungkin", l: 2 },
  { h: "应该", p: "yīnggāi", a: "seharusnya", l: 2 },
  { h: "希望", p: "xīwàng", a: "berharap", l: 2 },
  { h: "帮助", p: "bāngzhù", a: "membantu / bantuan", l: 2 },
  { h: "介绍", p: "jièshào", a: "memperkenalkan", l: 2 },
  { h: "准备", p: "zhǔnbèi", a: "bersiap / menyiapkan", l: 2 },
  { h: "开始", p: "kāishǐ", a: "mulai", l: 2 },
  { h: "完成", p: "wánchéng", a: "menyelesaikan", l: 2 },
  { h: "运动", p: "yùndòng", a: "olahraga", l: 2, c: "我每天运动。(Saya olahraga setiap hari.)" },
  { h: "跑步", p: "pǎobù", a: "berlari / lari", l: 2, c: "我喜欢跑步。(Saya suka lari.)" },
  { h: "身体", p: "shēntǐ", a: "tubuh / badan", l: 2 },
  { h: "健康", p: "jiànkāng", a: "sehat / kesehatan", l: 2 },
  { h: "累", p: "lèi", a: "lelah", l: 2 },
  { h: "忙", p: "máng", a: "sibuk", l: 2 },
  { h: "快", p: "kuài", a: "cepat", l: 2 },
  { h: "慢", p: "màn", a: "lambat", l: 2 },
  { h: "高", p: "gāo", a: "tinggi", l: 2 },
  { h: "新", p: "xīn", a: "baru", l: 2 },
  { h: "旧", p: "jiù", a: "lama / usang", l: 2 },
  { h: "贵", p: "guì", a: "mahal", l: 2 },
  { h: "便宜", p: "piányi", a: "murah", l: 2 },
  { h: "颜色", p: "yánsè", a: "warna", l: 2 },
  { h: "白", p: "bái", a: "putih", l: 2 },
  { h: "黑", p: "hēi", a: "hitam", l: 2 },
  { h: "红", p: "hóng", a: "merah", l: 2 },
  { h: "鸡蛋", p: "jīdàn", a: "telur ayam", l: 2 },
  { h: "牛奶", p: "niúnǎi", a: "susu sapi", l: 2 },
  { h: "羊肉", p: "yángròu", a: "daging kambing", l: 2 },
  { h: "鱼", p: "yú", a: "ikan", l: 2 },
  { h: "西瓜", p: "xīguā", a: "semangka", l: 2 },
  { h: "咖啡", p: "kāfēi", a: "kopi", l: 2 },
  { h: "时间", p: "shíjiān", a: "waktu", l: 2 },
  { h: "早上", p: "zǎoshang", a: "pagi", l: 2 },
  { h: "晚上", p: "wǎnshang", a: "malam", l: 2 },
  { h: "中午", p: "zhōngwǔ", a: "tengah hari / siang", l: 2 },
  { h: "小时", p: "xiǎoshí", a: "jam (durasi)", l: 2 },
  { h: "公司", p: "gōngsī", a: "perusahaan", l: 2 },
  { h: "问题", p: "wèntí", a: "masalah / pertanyaan", l: 2 },
  { h: "事情", p: "shìqing", a: "urusan / hal", l: 2 },
  { h: "意思", p: "yìsi", a: "arti / maksud", l: 2 },
  { h: "旅游", p: "lǚyóu", a: "berwisata", l: 2 },
  { h: "机场", p: "jīchǎng", a: "bandara", l: 2 },
  { h: "火车", p: "huǒchē", a: "kereta api", l: 2 },
  { h: "手机", p: "shǒujī", a: "ponsel / HP", l: 2 },

  // ===================== HSK 3 =====================
  { h: "经常", p: "jīngcháng", a: "sering", l: 3 },
  { h: "一般", p: "yìbān", a: "biasanya / umumnya", l: 3 },
  { h: "突然", p: "tūrán", a: "tiba-tiba", l: 3 },
  { h: "终于", p: "zhōngyú", a: "akhirnya", l: 3 },
  { h: "其实", p: "qíshí", a: "sebenarnya", l: 3 },
  { h: "比较", p: "bǐjiào", a: "relatif / membandingkan", l: 3 },
  { h: "特别", p: "tèbié", a: "khususnya / istimewa", l: 3 },
  { h: "重要", p: "zhòngyào", a: "penting", l: 3 },
  { h: "简单", p: "jiǎndān", a: "sederhana / mudah", l: 3 },
  { h: "容易", p: "róngyì", a: "mudah", l: 3 },
  { h: "难", p: "nán", a: "sulit", l: 3 },
  { h: "清楚", p: "qīngchu", a: "jelas", l: 3 },
  { h: "habit", p: "xíguàn", a: "kebiasaan", l: 3, c: "好习惯很重要。(Kebiasaan baik itu penting.)" },
  { h: "习惯", p: "xíguàn", a: "kebiasaan / terbiasa", l: 3 },
  { h: "决定", p: "juédìng", a: "memutuskan / keputusan", l: 3 },
  { h: "选择", p: "xuǎnzé", a: "memilih / pilihan", l: 3 },
  { h: "努力", p: "nǔlì", a: "berusaha keras", l: 3, c: "我会努力学习。(Saya akan belajar keras.)" },
  { h: "提高", p: "tígāo", a: "meningkatkan", l: 3 },
  { h: "影响", p: "yǐngxiǎng", a: "memengaruhi / pengaruh", l: 3 },
  { h: "解决", p: "jiějué", a: "menyelesaikan / mengatasi", l: 3 },
  { h: "检查", p: "jiǎnchá", a: "memeriksa", l: 3 },
  { h: "锻炼", p: "duànliàn", a: "berolahraga / melatih diri", l: 3, c: "锻炼身体很健康。(Olahraga menyehatkan badan.)" },
  { h: "健身", p: "jiànshēn", a: "fitness / nge-gym", l: 3 },
  { h: "比赛", p: "bǐsài", a: "pertandingan", l: 3 },
  { h: "成绩", p: "chéngjì", a: "hasil / prestasi", l: 3 },
  { h: "calories", p: "rèliàng", a: "kalori / energi panas", l: 3 },
  { h: "热量", p: "rèliàng", a: "kalori / energi panas", l: 3 },
  { h: "减肥", p: "jiǎnféi", a: "menurunkan berat badan", l: 3, c: "我想减肥。(Saya ingin menurunkan BB.)" },
  { h: "体重", p: "tǐzhòng", a: "berat badan", l: 3 },
  { h: "公斤", p: "gōngjīn", a: "kilogram (kg)", l: 3 },
  { h: "习题", p: "xítí", a: "soal latihan", l: 3 },
  { h: "复习", p: "fùxí", a: "mengulang pelajaran", l: 3 },
  { h: "练习", p: "liànxí", a: "berlatih / latihan", l: 3 },
  { h: "记得", p: "jìde", a: "ingat", l: 3 },
  { h: "忘记", p: "wàngjì", a: "lupa", l: 3 },
  { h: "burung", p: "niǎo", a: "burung", l: 3 },
  { h: "环境", p: "huánjìng", a: "lingkungan", l: 3 },
  { h: "城市", p: "chéngshì", a: "kota", l: 3 },
  { h: "地方", p: "dìfang", a: "tempat", l: 3 },
  { h: "附近", p: "fùjìn", a: "sekitar / dekat", l: 3 },
  { h: "邻居", p: "línjū", a: "tetangga", l: 3 },
  { h: "经理", p: "jīnglǐ", a: "manajer", l: 3 },
  { h: "护照", p: "hùzhào", a: "paspor", l: 3 },
  { h: "节目", p: "jiémù", a: "acara / program", l: 3 },
  { h: "新闻", p: "xīnwén", a: "berita", l: 3 },
  { h: "故事", p: "gùshi", a: "cerita", l: 3 },
  { h: "结婚", p: "jiéhūn", a: "menikah", l: 3 },
  { h: "年轻", p: "niánqīng", a: "muda", l: 3 },
  { h: "聪明", p: "cōngming", a: "pintar / cerdas", l: 3 },
  { h: "认真", p: "rènzhēn", a: "serius / tekun", l: 3 },
  { h: "满意", p: "mǎnyì", a: "puas", l: 3 },

  // ===================== HSK 4 =====================
  { h: "坚持", p: "jiānchí", a: "bertahan / konsisten", l: 4, c: "坚持锻炼很重要。(Konsisten berolahraga itu penting.)" },
  { h: "鼓励", p: "gǔlì", a: "menyemangati / dorongan", l: 4 },
  { h: "积极", p: "jījí", a: "aktif / positif", l: 4 },
  { h: "respect", p: "zūnzhòng", a: "menghormati", l: 4 },
  { h: "尊重", p: "zūnzhòng", a: "menghormati", l: 4 },
  { h: "建议", p: "jiànyì", a: "menyarankan / saran", l: 4 },
  { h: "judge", p: "pànduàn", a: "menilai / menentukan", l: 4 },
  { h: "判断", p: "pànduàn", a: "menilai / menentukan", l: 4 },
  { h: "考虑", p: "kǎolǜ", a: "mempertimbangkan", l: 4 },
  { h: "实际", p: "shíjì", a: "nyata / aktual", l: 4 },
  { h: "估计", p: "gūjì", a: "memperkirakan / estimasi", l: 4, c: "我估计明天会下雨。(Saya perkirakan besok hujan.)" },
  { h: "增加", p: "zēngjiā", a: "menambah / meningkat", l: 4 },
  { h: "减少", p: "jiǎnshǎo", a: "mengurangi / berkurang", l: 4 },
  { h: "改变", p: "gǎibiàn", a: "mengubah / perubahan", l: 4 },
  { h: "保持", p: "bǎochí", a: "menjaga / mempertahankan", l: 4, c: "保持健康很重要。(Menjaga kesehatan itu penting.)" },
  { h: "计划", p: "jìhuà", a: "rencana / merencanakan", l: 4 },
  { h: "目标", p: "mùbiāo", a: "target / tujuan", l: 4, c: "我的目标是减肥。(Targetku adalah menurunkan BB.)" },
  { h: "结果", p: "jiéguǒ", a: "hasil", l: 4 },
  { h: "过程", p: "guòchéng", a: "proses", l: 4 },
  { h: "方法", p: "fāngfǎ", a: "metode / cara", l: 4 },
  { h: "效果", p: "xiàoguǒ", a: "efek / hasil", l: 4 },
  { h: "经验", p: "jīngyàn", a: "pengalaman", l: 4 },
  { h: "能力", p: "nénglì", a: "kemampuan", l: 4 },
  { h: "机会", p: "jīhuì", a: "kesempatan", l: 4 },
  { h: "责任", p: "zérèn", a: "tanggung jawab", l: 4 },
  { h: "压力", p: "yālì", a: "tekanan / stres", l: 4 },
  { h: "情况", p: "qíngkuàng", a: "situasi / keadaan", l: 4 },
  { h: "区别", p: "qūbié", a: "perbedaan", l: 4 },
  { h: "标准", p: "biāozhǔn", a: "standar", l: 4 },
  { h: "重点", p: "zhòngdiǎn", a: "fokus / poin utama", l: 4 },
  { h: "肌肉", p: "jīròu", a: "otot", l: 4, c: "运动可以增加肌肉。(Olahraga bisa menambah otot.)" },
  { h: "脂肪", p: "zhīfáng", a: "lemak", l: 4 },
  { h: "营养", p: "yíngyǎng", a: "nutrisi / gizi", l: 4 },
  { h: "蛋白质", p: "dànbáizhì", a: "protein", l: 4 },
  { h: "饮食", p: "yǐnshí", a: "pola makan", l: 4 },
  { h: "肚子", p: "dùzi", a: "perut", l: 4, c: "我想减小肚子。(Saya ingin mengecilkan perut.)" },
  { h: "出汗", p: "chūhàn", a: "berkeringat", l: 4 },
  { h: "呼吸", p: "hūxī", a: "bernapas / napas", l: 4 },
  { h: "速度", p: "sùdù", a: "kecepatan", l: 4 },
  { h: "距离", p: "jùlí", a: "jarak", l: 4 },
  { h: "汗", p: "hàn", a: "keringat", l: 4 },
  { h: "羽毛球", p: "yǔmáoqiú", a: "bulu tangkis", l: 4, c: "周六我打羽毛球。(Sabtu saya main bulu tangkis.)" },
  { h: "毕业", p: "bìyè", a: "lulus / wisuda", l: 4 },
  { h: "professional", p: "zhuānyè", a: "jurusan / profesional", l: 4 },
  { h: "专业", p: "zhuānyè", a: "jurusan / profesional", l: 4 },
  { h: "收入", p: "shōurù", a: "pendapatan", l: 4 },
  { h: "节约", p: "jiéyuē", a: "berhemat", l: 4 },
  { h: "丰富", p: "fēngfù", a: "kaya / berlimpah", l: 4 },
  { h: "复杂", p: "fùzá", a: "rumit / kompleks", l: 4 },
  { h: "正式", p: "zhèngshì", a: "resmi / formal", l: 4 },
  { h: "优秀", p: "yōuxiù", a: "unggul / berprestasi", l: 4 },
];

/* ---------- TAMBAHAN KOSAKATA HSK 1-4 (batch 2) ---------- */
const HSK_VOCAB_2 = [
  // ===== HSK 1 (tambahan) =====
  { h: "四", p: "sì", a: "empat (4)", l: 1 },
  { h: "六", p: "liù", a: "enam (6)", l: 1 },
  { h: "七", p: "qī", a: "tujuh (7)", l: 1 },
  { h: "八", p: "bā", a: "delapan (8)", l: 1 },
  { h: "九", p: "jiǔ", a: "sembilan (9)", l: 1 },
  { h: "零", p: "líng", a: "nol (0)", l: 1 },
  { h: "这", p: "zhè", a: "ini", l: 1 },
  { h: "那", p: "nà", a: "itu", l: 1 },
  { h: "哪", p: "nǎ", a: "yang mana", l: 1 },
  { h: "谁", p: "shéi", a: "siapa", l: 1 },
  { h: "什么", p: "shénme", a: "apa", l: 1 },
  { h: "几", p: "jǐ", a: "berapa (jumlah kecil)", l: 1 },
  { h: "多少", p: "duōshao", a: "berapa (jumlah)", l: 1 },
  { h: "怎么", p: "zěnme", a: "bagaimana", l: 1 },
  { h: "为什么", p: "wèishénme", a: "kenapa / mengapa", l: 1 },
  { h: "和", p: "hé", a: "dan / dengan", l: 1 },
  { h: "很", p: "hěn", a: "sangat", l: 1 },
  { h: "太", p: "tài", a: "terlalu", l: 1 },
  { h: "也", p: "yě", a: "juga", l: 1 },
  { h: "都", p: "dōu", a: "semua / semuanya", l: 1 },
  { h: "有", p: "yǒu", a: "ada / punya", l: 1 },
  { h: "没", p: "méi", a: "tidak (ada/punya)", l: 1 },
  { h: "在", p: "zài", a: "di / sedang", l: 1 },
  { h: "会", p: "huì", a: "bisa / akan", l: 1 },
  { h: "能", p: "néng", a: "bisa / mampu", l: 1 },
  { h: "想", p: "xiǎng", a: "ingin / memikirkan", l: 1 },
  { h: "做", p: "zuò", a: "melakukan / membuat", l: 1 },
  { h: "坐", p: "zuò", a: "duduk", l: 1 },
  { h: "爸爸", p: "bàba", a: "ayah", l: 1 },
  { h: "妈妈", p: "māma", a: "ibu", l: 1 },
  { h: "儿子", p: "érzi", a: "anak laki-laki", l: 1 },
  { h: "女儿", p: "nǚ'ér", a: "anak perempuan", l: 1 },
  { h: "医生", p: "yīshēng", a: "dokter", l: 1 },
  { h: "医院", p: "yīyuàn", a: "rumah sakit", l: 1 },
  { h: "商店", p: "shāngdiàn", a: "toko", l: 1 },
  { h: "电脑", p: "diànnǎo", a: "komputer", l: 1 },
  { h: "电视", p: "diànshì", a: "televisi", l: 1 },
  { h: "电影", p: "diànyǐng", a: "film", l: 1 },
  { h: "苹果", p: "píngguǒ", a: "apel", l: 1 },
  { h: "热", p: "rè", a: "panas", l: 1 },
  { h: "冷", p: "lěng", a: "dingin", l: 1 },
  { h: "漂亮", p: "piàoliang", a: "cantik", l: 1 },
  { h: "高兴", p: "gāoxìng", a: "senang / gembira", l: 1 },
  { h: "多", p: "duō", a: "banyak", l: 1 },
  { h: "少", p: "shǎo", a: "sedikit", l: 1 },

  // ===== HSK 2 (tambahan) =====
  { h: "教室", p: "jiàoshì", a: "ruang kelas", l: 2 },
  { h: "房间", p: "fángjiān", a: "kamar", l: 2 },
  { h: "宾馆", p: "bīnguǎn", a: "hotel", l: 2 },
  { h: "服务员", p: "fúwùyuán", a: "pelayan", l: 2 },
  { h: "妻子", p: "qīzi", a: "istri", l: 2 },
  { h: "丈夫", p: "zhàngfu", a: "suami", l: 2 },
  { h: "孩子", p: "háizi", a: "anak", l: 2 },
  { h: "左边", p: "zuǒbian", a: "sebelah kiri", l: 2 },
  { h: "右边", p: "yòubian", a: "sebelah kanan", l: 2 },
  { h: "旁边", p: "pángbiān", a: "di samping", l: 2 },
  { h: "外面", p: "wàimiàn", a: "di luar", l: 2 },
  { h: "自行车", p: "zìxíngchē", a: "sepeda", l: 2 },
  { h: "路", p: "lù", a: "jalan", l: 2 },
  { h: "票", p: "piào", a: "tiket / karcis", l: 2 },
  { h: "报纸", p: "bàozhǐ", a: "koran", l: 2 },
  { h: "手表", p: "shǒubiǎo", a: "jam tangan", l: 2 },
  { h: "眼睛", p: "yǎnjīng", a: "mata", l: 2 },
  { h: "雪", p: "xuě", a: "salju", l: 2 },
  { h: "晴", p: "qíng", a: "cerah", l: 2 },
  { h: "阴", p: "yīn", a: "mendung", l: 2 },
  { h: "已经", p: "yǐjīng", a: "sudah", l: 2 },
  { h: "正在", p: "zhèngzài", a: "sedang (berlangsung)", l: 2 },
  { h: "一起", p: "yìqǐ", a: "bersama", l: 2 },
  { h: "别", p: "bié", a: "jangan", l: 2 },
  { h: "最", p: "zuì", a: "paling", l: 2 },
  { h: "真", p: "zhēn", a: "benar-benar / sungguh", l: 2 },
  { h: "非常", p: "fēicháng", a: "sangat / luar biasa", l: 2 },
  { h: "长", p: "cháng", a: "panjang", l: 2 },
  { h: "远", p: "yuǎn", a: "jauh", l: 2 },
  { h: "近", p: "jìn", a: "dekat", l: 2 },
  { h: "错", p: "cuò", a: "salah", l: 2 },
  { h: "对", p: "duì", a: "benar / betul", l: 2 },
  { h: "一样", p: "yíyàng", a: "sama", l: 2 },
  { h: "让", p: "ràng", a: "membiarkan / menyuruh", l: 2 },
  { h: "给", p: "gěi", a: "memberi / untuk", l: 2 },
  { h: "找", p: "zhǎo", a: "mencari", l: 2 },
  { h: "送", p: "sòng", a: "mengantar / memberi", l: 2 },
  { h: "唱歌", p: "chànggē", a: "menyanyi", l: 2 },
  { h: "跳舞", p: "tiàowǔ", a: "menari", l: 2 },
  { h: "游泳", p: "yóuyǒng", a: "berenang", l: 2 },
  { h: "起床", p: "qǐchuáng", a: "bangun tidur", l: 2 },
  { h: "睡觉", p: "shuìjiào", a: "tidur", l: 2 },

  // ===== HSK 3 (tambahan) =====
  { h: "关系", p: "guānxi", a: "hubungan", l: 3 },
  { h: "礼物", p: "lǐwù", a: "hadiah", l: 3 },
  { h: "季节", p: "jìjié", a: "musim", l: 3 },
  { h: "春", p: "chūn", a: "musim semi", l: 3 },
  { h: "夏", p: "xià", a: "musim panas", l: 3 },
  { h: "秋", p: "qiū", a: "musim gugur", l: 3 },
  { h: "冬", p: "dōng", a: "musim dingin", l: 3 },
  { h: "太阳", p: "tàiyáng", a: "matahari", l: 3 },
  { h: "月亮", p: "yuèliang", a: "bulan (di langit)", l: 3 },
  { h: "河", p: "hé", a: "sungai", l: 3 },
  { h: "山", p: "shān", a: "gunung", l: 3 },
  { h: "树", p: "shù", a: "pohon", l: 3 },
  { h: "花", p: "huā", a: "bunga", l: 3 },
  { h: "动物", p: "dòngwù", a: "hewan", l: 3 },
  { h: "历史", p: "lìshǐ", a: "sejarah", l: 3 },
  { h: "文化", p: "wénhuà", a: "budaya", l: 3 },
  { h: "数学", p: "shùxué", a: "matematika", l: 3 },
  { h: "同事", p: "tóngshì", a: "rekan kerja", l: 3 },
  { h: "客人", p: "kèrén", a: "tamu", l: 3 },
  { h: "司机", p: "sījī", a: "sopir", l: 3 },
  { h: "头发", p: "tóufa", a: "rambut", l: 3 },
  { h: "脸", p: "liǎn", a: "wajah", l: 3 },
  { h: "耳朵", p: "ěrduo", a: "telinga", l: 3 },
  { h: "鼻子", p: "bízi", a: "hidung", l: 3 },
  { h: "嘴", p: "zuǐ", a: "mulut", l: 3 },
  { h: "腿", p: "tuǐ", a: "kaki (paha-betis)", l: 3 },
  { h: "脚", p: "jiǎo", a: "kaki (telapak)", l: 3 },
  { h: "着急", p: "zháojí", a: "cemas / gelisah", l: 3 },
  { h: "害怕", p: "hàipà", a: "takut", l: 3 },
  { h: "担心", p: "dānxīn", a: "khawatir", l: 3 },
  { h: "奇怪", p: "qíguài", a: "aneh", l: 3 },
  { h: "安静", p: "ānjìng", a: "tenang / sunyi", l: 3 },
  { h: "干净", p: "gānjìng", a: "bersih", l: 3 },
  { h: "方便", p: "fāngbiàn", a: "praktis / mudah", l: 3 },
  { h: "新鲜", p: "xīnxiān", a: "segar", l: 3 },
  { h: "甜", p: "tián", a: "manis", l: 3 },
  { h: "饿", p: "è", a: "lapar", l: 3, c: "我饿了。(Saya lapar.)" },
  { h: "渴", p: "kě", a: "haus", l: 3 },
  { h: "饱", p: "bǎo", a: "kenyang", l: 3 },
  { h: "瘦", p: "shòu", a: "kurus", l: 3, c: "我想变瘦。(Saya ingin jadi kurus.)" },
  { h: "胖", p: "pàng", a: "gemuk", l: 3, c: "我有点胖。(Saya agak gemuk.)" },
  { h: "总是", p: "zǒngshì", a: "selalu", l: 3 },
  { h: "一定", p: "yídìng", a: "pasti / tentu", l: 3 },
  { h: "必须", p: "bìxū", a: "harus / wajib", l: 3 },
  { h: "需要", p: "xūyào", a: "perlu / membutuhkan", l: 3 },
  { h: "可以", p: "kěyǐ", a: "boleh / bisa", l: 3 },

  // ===== HSK 4 (tambahan) =====
  { h: "信心", p: "xìnxīn", a: "keyakinan / percaya diri", l: 4 },
  { h: "态度", p: "tàidu", a: "sikap", l: 4 },
  { h: "性格", p: "xìnggé", a: "watak / kepribadian", l: 4 },
  { h: "精神", p: "jīngshén", a: "semangat / jiwa", l: 4 },
  { h: "顺利", p: "shùnlì", a: "lancar", l: 4 },
  { h: "麻烦", p: "máfan", a: "repot / merepotkan", l: 4 },
  { h: "困难", p: "kùnnan", a: "kesulitan / sulit", l: 4 },
  { h: "危险", p: "wēixiǎn", a: "bahaya / berbahaya", l: 4 },
  { h: "安全", p: "ānquán", a: "aman / keamanan", l: 4 },
  { h: "体育", p: "tǐyù", a: "olahraga (pendidikan jasmani)", l: 4 },
  { h: "教练", p: "jiàoliàn", a: "pelatih", l: 4, c: "我的健身教练很严格。(Pelatih gym-ku tegas.)" },
  { h: "动作", p: "dòngzuò", a: "gerakan", l: 4 },
  { h: "运动员", p: "yùndòngyuán", a: "atlet", l: 4 },
  { h: "放松", p: "fàngsōng", a: "rileks / santai", l: 4, c: "运动后要放松肌肉。(Setelah olahraga, rilekskan otot.)" },
  { h: "紧张", p: "jǐnzhāng", a: "tegang / gugup", l: 4 },
  { h: "重复", p: "chóngfù", a: "mengulang", l: 4 },
  { h: "平衡", p: "pínghéng", a: "keseimbangan", l: 4 },
  { h: "恢复", p: "huīfù", a: "pulih / memulihkan", l: 4 },
  { h: "受伤", p: "shòushāng", a: "cedera / terluka", l: 4 },
  { h: "表示", p: "biǎoshì", a: "menyatakan / menunjukkan", l: 4 },
  { h: "表扬", p: "biǎoyáng", a: "memuji", l: 4 },
  { h: "批评", p: "pīpíng", a: "mengkritik", l: 4 },
  { h: "怀疑", p: "huáiyí", a: "meragukan / curiga", l: 4 },
  { h: "拒绝", p: "jùjué", a: "menolak", l: 4 },
  { h: "接受", p: "jiēshòu", a: "menerima", l: 4 },
  { h: "同意", p: "tóngyì", a: "setuju", l: 4 },
  { h: "反对", p: "fǎnduì", a: "menentang", l: 4 },
  { h: "支持", p: "zhīchí", a: "mendukung", l: 4 },
  { h: "完全", p: "wánquán", a: "sepenuhnya / sama sekali", l: 4 },
  { h: "主要", p: "zhǔyào", a: "utama", l: 4 },
  { h: "直接", p: "zhíjiē", a: "langsung", l: 4 },
  { h: "准确", p: "zhǔnquè", a: "akurat / tepat", l: 4 },
  { h: "详细", p: "xiángxì", a: "rinci / detail", l: 4 },
  { h: "普遍", p: "pǔbiàn", a: "umum / merata", l: 4 },
  { h: "流行", p: "liúxíng", a: "populer / tren", l: 4 },
  { h: "著名", p: "zhùmíng", a: "terkenal", l: 4 },
  { h: "重新", p: "chóngxīn", a: "ulang dari awal", l: 4 },
  { h: "互相", p: "hùxiāng", a: "saling", l: 4 },
  { h: "安排", p: "ānpái", a: "mengatur / menjadwalkan", l: 4 },
  { h: "整理", p: "zhěnglǐ", a: "merapikan / menyusun", l: 4 },
  { h: "提供", p: "tígōng", a: "menyediakan", l: 4 },
  { h: "获得", p: "huòdé", a: "memperoleh / meraih", l: 4 },
  { h: "适合", p: "shìhé", a: "cocok / sesuai", l: 4 },
  { h: "适应", p: "shìyìng", a: "beradaptasi", l: 4 },
  { h: "坚强", p: "jiānqiáng", a: "tegar / tangguh", l: 4 },
  { h: "勇敢", p: "yǒnggǎn", a: "berani", l: 4 },
];

// Bersihkan entri "placeholder" (kunci bahasa Inggris) yang dipakai saat penyusunan:
// hapus entri yang hanzi-nya bukan karakter China. Lalu gabung kedua batch.
const VOCAB = HSK_VOCAB.concat(HSK_VOCAB_2).filter(v => /[一-鿿]/.test(v.h))
  .map((v, i) => ({ id: "v" + i, ...v }));

/* ---------- LIBRARY PROGRAM LATIHAN ----------
   Kumpulan template program. Bisa dipilih bebas per hari di aplikasi.
   Disusun untuk fat loss + mengecilkan perut (banyak compound + core + kardio). */
const PROGRAM_LIB = {
  upper: {
    nama: "Upper Body", emoji: "💪", fokus: "Dada, punggung, lengan",
    exercises: [
      { n: "Pull-up / Lat Pulldown", d: "3 × 8-12" },
      { n: "Bench Press / Push-up", d: "3 × 10-12" },
      { n: "Seated Row", d: "3 × 12" },
      { n: "Overhead Press", d: "3 × 10" },
      { n: "Bicep Curl", d: "3 × 12" },
      { n: "Tricep Dip", d: "3 × 12" },
      { n: "Plank (core)", d: "3 × 45 dtk" },
    ], cardio: null, target: 45,
  },
  lari_bw: {
    nama: "Lari + Bodyweight", emoji: "🏃", fokus: "Kardio & ketahanan",
    exercises: [
      { n: "Push-up", d: "4 × 15" },
      { n: "Bodyweight Squat", d: "4 × 20" },
      { n: "Walking Lunges", d: "3 × 12/kaki" },
      { n: "Mountain Climbers", d: "3 × 30 dtk" },
      { n: "Burpees", d: "3 × 10" },
      { n: "Plank (core)", d: "3 × 45 dtk" },
    ], cardio: { jenis: "Lari", durasi: 30 }, target: 45,
  },
  lower: {
    nama: "Lower Body", emoji: "🦵", fokus: "Kaki & glutes",
    exercises: [
      { n: "Squat (barbell/dumbbell)", d: "4 × 8-12" },
      { n: "Romanian Deadlift", d: "3 × 10" },
      { n: "Leg Press", d: "3 × 12" },
      { n: "Walking Lunges", d: "3 × 12/kaki" },
      { n: "Calf Raise", d: "4 × 15" },
      { n: "Hanging Leg Raise (core)", d: "3 × 12" },
    ], cardio: null, target: 45,
  },
  trisep_bahu: {
    nama: "Trisep & Bahu", emoji: "🏋️", fokus: "Bahu & trisep",
    exercises: [
      { n: "Overhead Press", d: "4 × 8-12" },
      { n: "Lateral Raise", d: "3 × 15" },
      { n: "Front Raise", d: "3 × 12" },
      { n: "Tricep Pushdown", d: "3 × 12" },
      { n: "Skull Crusher", d: "3 × 12" },
      { n: "Face Pull", d: "3 × 15" },
      { n: "Bicycle Crunch (core)", d: "3 × 20" },
    ], cardio: null, target: 45,
  },
  rest_lari: {
    nama: "Istirahat / Lari Ringan", emoji: "😌", fokus: "Recovery aktif",
    exercises: [
      { n: "Stretching / Mobility", d: "10-15 mnt" },
      { n: "Plank (opsional)", d: "3 × 45 dtk" },
    ], cardio: { jenis: "Lari ringan (opsional)", durasi: 30 }, target: 30,
  },
  dada_bicep: {
    nama: "Dada & Bicep + Badminton", emoji: "🏸", fokus: "Dada, bicep & badminton (14.00-16.00)",
    exercises: [
      { n: "Bench Press", d: "4 × 8-12" },
      { n: "Incline Dumbbell Press", d: "3 × 10" },
      { n: "Chest Fly", d: "3 × 12" },
      { n: "Push-up", d: "3 × max" },
      { n: "Barbell/Dumbbell Curl", d: "3 × 12" },
      { n: "Hammer Curl", d: "3 × 12" },
      { n: "Badminton 🏸", d: "14.00 - 16.00" },
    ], cardio: { jenis: "Badminton", durasi: 120 }, target: 60,
  },
  lari_kardio: {
    nama: "Lari + Kardio", emoji: "🔥", fokus: "Kardio & pembakaran lemak + timbang BB",
    exercises: [
      { n: "Lari", d: "30-40 mnt" },
      { n: "HIIT (sprint interval)", d: "10 mnt" },
      { n: "Jumping Jack", d: "3 × 40" },
      { n: "Russian Twist (core)", d: "3 × 20" },
      { n: "Leg Raise (core)", d: "3 × 15" },
      { n: "Plank (core)", d: "3 × 60 dtk" },
    ], cardio: { jenis: "Lari + Kardio", durasi: 40 }, target: 50,
  },
  // ---- Template tambahan (variasi) ----
  full_body: {
    nama: "Full Body", emoji: "🧱", fokus: "Seluruh tubuh (efisien)",
    exercises: [
      { n: "Squat", d: "3 × 10" },
      { n: "Bench Press / Push-up", d: "3 × 10" },
      { n: "Bent-over Row", d: "3 × 10" },
      { n: "Overhead Press", d: "3 × 10" },
      { n: "Romanian Deadlift", d: "3 × 10" },
      { n: "Plank (core)", d: "3 × 45 dtk" },
    ], cardio: null, target: 45,
  },
  push: {
    nama: "Push (Dorong)", emoji: "🤜", fokus: "Dada, bahu, trisep",
    exercises: [
      { n: "Bench Press", d: "4 × 8-12" },
      { n: "Overhead Press", d: "3 × 10" },
      { n: "Incline Dumbbell Press", d: "3 × 10" },
      { n: "Lateral Raise", d: "3 × 15" },
      { n: "Tricep Pushdown", d: "3 × 12" },
      { n: "Plank (core)", d: "3 × 45 dtk" },
    ], cardio: null, target: 45,
  },
  pull: {
    nama: "Pull (Tarik)", emoji: "🤛", fokus: "Punggung & bicep",
    exercises: [
      { n: "Pull-up / Lat Pulldown", d: "4 × 8-12" },
      { n: "Seated Row", d: "3 × 12" },
      { n: "Face Pull", d: "3 × 15" },
      { n: "Bicep Curl", d: "3 × 12" },
      { n: "Hammer Curl", d: "3 × 12" },
      { n: "Hanging Leg Raise (core)", d: "3 × 12" },
    ], cardio: null, target: 45,
  },
  core_perut: {
    nama: "Core / Perut", emoji: "🎯", fokus: "Khusus kecilkan perut",
    exercises: [
      { n: "Plank", d: "3 × 60 dtk" },
      { n: "Bicycle Crunch", d: "3 × 20" },
      { n: "Russian Twist", d: "3 × 20" },
      { n: "Leg Raise", d: "3 × 15" },
      { n: "Mountain Climbers", d: "3 × 30 dtk" },
      { n: "Dead Bug", d: "3 × 12" },
    ], cardio: { jenis: "Lari ringan (opsional)", durasi: 20 }, target: 35,
  },
  kardio_hiit: {
    nama: "Kardio / HIIT", emoji: "⚡", fokus: "Bakar kalori maksimal",
    exercises: [
      { n: "HIIT (sprint interval)", d: "15 mnt" },
      { n: "Burpees", d: "4 × 12" },
      { n: "Jumping Jack", d: "4 × 40" },
      { n: "High Knees", d: "3 × 40 dtk" },
      { n: "Plank (core)", d: "3 × 45 dtk" },
    ], cardio: { jenis: "HIIT", durasi: 25 }, target: 35,
  },
  lari_only: {
    nama: "Lari Saja", emoji: "🏃‍♂️", fokus: "Kardio jarak jauh",
    exercises: [
      { n: "Pemanasan jalan cepat", d: "5 mnt" },
      { n: "Lari", d: "30-45 mnt" },
      { n: "Pendinginan + stretching", d: "5 mnt" },
    ], cardio: { jenis: "Lari", durasi: 40 }, target: 40,
  },
  badminton: {
    nama: "Badminton", emoji: "🏸", fokus: "Kardio + kelincahan",
    exercises: [
      { n: "Pemanasan", d: "10 mnt" },
      { n: "Badminton", d: "90-120 mnt" },
    ], cardio: { jenis: "Badminton", durasi: 120 }, target: 60,
  },
  rest: {
    nama: "Istirahat Total", emoji: "🛌", fokus: "Pemulihan penuh",
    exercises: [
      { n: "Stretching ringan (opsional)", d: "10 mnt" },
      { n: "Jalan santai (opsional)", d: "15-20 mnt" },
    ], cardio: null, target: 0,
  },
  custom: {
    nama: "Custom (bebas)", emoji: "✍️", fokus: "Catat latihanmu sendiri",
    exercises: [], cardio: null, target: 30,
  },
};

// Jadwal default mingguan (key = getDay(): 0=Minggu .. 6=Sabtu)
const SCHEDULE = { 1: "upper", 2: "lari_bw", 3: "lower", 4: "trisep_bahu", 5: "rest_lari", 6: "dada_bicep", 0: "lari_kardio" };

// PROGRAM[day] = template default hari itu (kompatibel dgn kode lama)
const PROGRAM = {};
for (const d in SCHEDULE) PROGRAM[d] = PROGRAM_LIB[SCHEDULE[d]];

const NAMA_HARI = ["Minggu", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu"];

// Perkiraan kalori terbakar per menit (kasar, untuk estimasi)
const KALORI_PER_MENIT = {
  "Lari": 11,
  "Lari ringan (opsional)": 8,
  "Badminton": 7,
  "Lari + Kardio": 10,
  "Angkat beban / Gym": 6,
  "HIIT": 12,
  "Lainnya": 6,
};

/* ---------- REFERENSI KALORI MAKANAN (per porsi umum) ---------- */
const FOOD_REF = [
  { n: "Nasi putih (1 centong ~100g)", k: 175 },
  { n: "Nasi merah (100g)", k: 150 },
  { n: "Ayam goreng (1 potong)", k: 260 },
  { n: "Ayam dada rebus (100g)", k: 165 },
  { n: "Telur rebus (1 butir)", k: 78 },
  { n: "Telur dadar (1 butir)", k: 150 },
  { n: "Tahu (1 potong)", k: 80 },
  { n: "Tempe (1 potong)", k: 100 },
  { n: "Ikan bakar (100g)", k: 180 },
  { n: "Daging sapi (100g)", k: 250 },
  { n: "Sayur bayam (1 mangkok)", k: 40 },
  { n: "Tumis kangkung (1 porsi)", k: 90 },
  { n: "Mie instan (1 bungkus)", k: 380 },
  { n: "Roti tawar (1 lembar)", k: 80 },
  { n: "Pisang (1 buah)", k: 105 },
  { n: "Apel (1 buah)", k: 95 },
  { n: "Susu (1 gelas)", k: 120 },
  { n: "Kopi susu gula (1 gelas)", k: 150 },
  { n: "Teh manis (1 gelas)", k: 90 },
  { n: "Air putih", k: 0 },
  { n: "Gorengan (1 buah)", k: 130 },
  { n: "Bakso (1 mangkok)", k: 300 },
  { n: "Soto ayam (1 mangkok)", k: 312 },
  { n: "Nasi goreng (1 piring)", k: 330 },
  { n: "Whey protein (1 scoop)", k: 120 },
  { n: "Oatmeal (40g)", k: 150 },
  { n: "Kacang almond (10 butir)", k: 70 },
  { n: "Alpukat (1/2 buah)", k: 160 },
];
